### ISSUE TITLE
只能更新64位版本的core

### ISSUE THREAD

**Issue by Silvmoon** [Jrohy/v2rayN#1]
只能更新64位的v2ray core，可是系统是32位的，能否增加支持更新32位core功能？谢谢！

**Comment by Jrohy** [comment]
这点确实可以完善下

**Comment by Silvmoon** [comment]
期待😁

**Comment by Jrohy** [comment]
新版本加入了32位的v2ray更新下载，欢迎测试下:
https://github.com/Jrohy/v2rayN/releases/tag/1.24.2

**Comment by Silvmoon** [comment]
32位v2ray顺利更新 感谢作者 更新更方便了
