### ISSUE TITLE
批量链接导入经常出现 “转换配置文件失败”

### ISSUE THREAD

**Issue by Justsoos** [Jrohy/v2rayN#10]
可能是 url 不符合规范，或配置文件无法读取？
希望能：
1，批量导入时，能跳过配置错误的 URL，继续导入其余 URL，并给出不能导入的 URL 的 textbox 详情，或 log 全部导入成功和失败 URL，逐一标记，方便检查
2，能明确错误具体情况，这个提示不是很明确。

![image](https://user-images.githubusercontent.com/3480043/42671836-e066f1ee-8694-11e8-90c3-93a3c0c7f90a.png)

**Comment by Justsoos** [comment]
另外，我怎么好像用到了一个还没发行的版本？？？6月24日的？？？

![image](https://user-images.githubusercontent.com/3480043/42671950-91aa8204-8695-11e8-956a-252d98a65e5c.png)

**Comment by Jrohy** [comment]
请用原版，v2rayN已经不维护了

**Comment by Justsoos** [comment]
发现有不少这样写地址的，不知道是什么客户端生成的，用的人还特别多，我把 base64 解开了，方便看

vmess://{"add":"1.1.1.1","aid":"64","host":"","id":"42b0f1ec-fd05-49df-99b6-6f08a97cc95c","net":"tcp","path":"","port":"8000","ps":"无法导入","tls":"","type":"none","v":"2"}

这种地址，目前你的版本 v2rayN 无法识别。

**Comment by Justsoos** [comment]
好的。那关了

**Comment by Justsoos** [comment]
使用了 https://github.com/2dust/v2rayN/releases  版本，这些url都能导入。。。。看来你需要提示一下了，很多用户不知道这事儿。

**Comment by Jrohy** [comment]
已经在项目首页作说明
