### ISSUE TITLE
主界面菜单选择从剪贴板导入出错

### ISSUE THREAD

**Issue by Yamazaki-wu** [Jrohy/v2rayN#2]
复制的信息只能是纯的vmess链接，如果包含其他文字信息，选择剪贴板导入就报错。
这点建议改进一下，SSR和SSRR都无视复制文字内容，只要包含SSR链接均可正常导入。SS没有测试过是否也可以。

**Comment by Jrohy** [comment]
ss和vmess一样的，可以做下处理导入时去掉中文字符

**Comment by Yamazaki-wu** [comment]
SSR导入识别时貌似不止有中文字符啊，大概自动辨识从ssr://开始的base64字符串吧，然后结束符不知道是否会判断。

**Comment by Jrohy** [comment]
新版支持了，你可以测试下:
https://github.com/Jrohy/v2rayN/releases/tag/1.24.2
正常的base64都能导成功，除非里面有参些杂质，则忽略继续导能导的

**Comment by Yamazaki-wu** [comment]
新版本测试过了，已经能自动辨识vmess链接正常导入。感谢！
那如果一次性导入多个的话还是托盘图标右键批量导入是吧。
对了，再提个小建议，界面打开的时候任务栏没有bar，被其他软件界面覆盖掉之后挺不方便的。请问是否可以添加这个小功能？
还有，切换不同的线路时只能用右键菜单中设置为活动服务器才可以？是否可以直接点选最左侧的√来实现？

**Comment by Yamazaki-wu** [comment]
啊，忘记说了。请问根据系统自动更新v2ray core的选项在哪里？

**Comment by Yamazaki-wu** [comment]
哦，看到了。在托盘图标右键。请忽略那个问题。

**Comment by Jrohy** [comment]
√只是表示那个当前生效的服务器的字符串，绑定不了点击事件的。
第一个建议不是特别懂，如果手动操作不是很麻烦的话也没必要代码实现

**Comment by Yamazaki-wu** [comment]
我说的第一个就是一般软件最小化时都在任务栏上有一条bar，而这个软件最小化时直接到托盘去了。

**Comment by Yamazaki-wu** [comment]
当然我只是询问一下，生效服务器有没有更快捷的切换方式。
