### ISSUE TITLE
是否可以考虑摆脱原 v2rayN 的配置方法，启用独立config 

### ISSUE THREAD

**Issue by Justsoos** [Jrohy/v2rayN#3]
目前的 v2rayN 配置大概只考虑了不到10个参数取值，其他都是内置固定的。这就引入一个问题，如果配置有这些参数之外自定义 config 参数，就无法运行。而且有人定义了不同字段，也会引发错乱。-- 说实话，v2ray的配置传递现在是真的乱，一个软件搞一个标准，谁和谁都不一样。

比如 https://free-ss.site/ 共享的两个配置，导入v2rayN 就没法用，它的路由和其他一些配置和 v2rayN 默认的不同。只能手动用 cli来运行 `v2ray.exe -config config.json`，这里 config.json 是独立文件。
由于与ssr，ss完全不同，v2ray 服务器端生产出来的 config.json 包含所有密钥--参数，可以考虑什么时候放弃v2rayN 的原有模式，否则无法使用这些独立配置。

**Comment by Jrohy** [comment]
https://free-ss.site/
里面的可以扫二维码导入来用，v2rayN的变化大的不会考虑。暂时只做体验上的优化

**Comment by Justsoos** [comment]
我可能没说明白，free-ss 那个账号只是一个例子，它只能用单独命令行，单独 config.json 文件方式启动 v2ray ，v2rayN 无论如何导入，都不能正常工作（可能今天它改了参数，但至少昨天是不能用的），它的 routing 和其他几个字段，与 v2rayN 默认的冲突，导致账号无法使用。

v2ray 就是因为它太灵活了，配置参数太多，才会有这样的问题。

不改就不改吧，这个 v2rayN 本来底子也不好，为了将就能用，减少了很多参数设置能力，妥协出了很多问题。包括 服务器端如果禁止mux，用 config.json 无法携带这个参数 -- 最终就是无法正常使用。

**Comment by Jrohy** [comment]
不用config.json配置文件，而是用二维码扫描导入，扫进去是能用的

**Comment by Justsoos** [comment]
那就是 free-ss 改过了，前天时候时不能用的，一个朋友问我，我去测过，不论二维码，还是 uri，还是按照参数填写。下载了config.json 对比，和 v2rayN 冲突。

这只是一个公开的例子，问题的核心不是 free-ss 这网站，而是 v2rayN 只选择了不到10个可定义参数，以及背后是一个写死的 config.json 模板的问题

**Comment by MizunaRei** [comment]
你做的客户端有URL导入设置，真是方便多了。能做个Mac客户端吗？

**Comment by Jrohy** [comment]
不用mac, 也不会写mac的代码

**Comment by MizunaRei** [comment]
感謝您為v2ray的貢獻。

**Comment by Jrohy** [comment]
不客气，只是改下方便自己用，最应该感谢还是原作者
