### ISSUE TITLE
直连模式

### ISSUE THREAD

**Issue by Maxilme** [Jrohy/v2rayN#5]
希望能在系统代理模式增加一个直连模式，这样只需要通过浏览器代理，而不是在电脑系统里面加代理

**Comment by Jrohy** [comment]
有空研究下

**Comment by Maxilme** [comment]
@Jrohy 已经加了直连模式了吗

**Comment by Maxilme** [comment]
@Jrohy 已经加了直连模式了吗

**Comment by Maxilme** [comment]
@Jrohy 已经加了直连模式了吗

**Comment by Jrohy** [comment]
还没，主要是没什么这种应用场景，没什么动力去研究😂，能介绍下有什么场景许愿这样吗

**Comment by Maxilme** [comment]
因为我经常会多个浏览器切换，有些浏览器没有装代理插件，打开网页就会比较慢

**Comment by Jrohy** [comment]
不好意思了，个人真的没这种需要，个人比较有需要的可能还有ssr的节点订阅

**Comment by Maxilme** [comment]
ok 节点订阅确实是个人用户需求最高的
