### ISSUE TITLE
更新v2core失败

### ISSUE THREAD

**Issue by liangxyz** [Jrohy/v2rayN#6]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常更新v2 core

### 实际行为
程序下载最新版v2 core解压后，提示中央目录损坏

### 复现方法
1.打开gui界面
2.点击检查v2 core更新
3.等待下载完成就会提示

### 日志信息,位置在当前目录下的guiLogs
<details>

```
在这里粘贴日志
```
</details>

**Comment by Jrohy** [comment]
目前有两种更新core的方式，一种最早是我集成在托盘右键菜单里的，一种是后来原版也加上这功能，我也加上去了在主界面的检查更新按钮子菜单里。两种方式下载完解压处理记得不太一样，你可以试试

**Comment by Justsoos** [comment]
最好改掉，不要直接更新到系统windows\system32文件夹下（会留下系统垃圾，并且可能引发版本会冲突），很多人其实就是独立目录使用，更新到本地目录应该是首选判断，然后再用 系统 path 找，如果有 v2ray.exe 的目录，就更新进去。

**Comment by Jrohy** [comment]
是更新到v2rayN执行程序同一目录的，托盘右键更新是会删除下载的压缩包

**Comment by Justsoos** [comment]
不记得具体版本，应该是一个月以前一个版本，试用了一下你的v2rayN更新，然后就没找到更新包。。。。
后来在 cmd 里直接敲命令竟然发现能执行 v2ray.exe 才发现是被下到了system32 目录里。。。
之后再没用过这个功能。。。

**Comment by liangxyz** [comment]
是的，我也是搜索发现下载到system32目录了

**Comment by Jrohy** [comment]
一开始设计就是下载Core都是下在和v2rayN同一目录，不知道是不是下载不了core才触发
