### ISSUE TITLE
二维码扫描问题

### ISSUE THREAD

**Issue by konbar** [Jrohy/v2rayN#7]
今天扫描SS二维码却全被识别成了VMESS的服务器信息，造成无法正常访问，后来查询是二维扫描错把SS服务器全部识别成了VMESS服务器，希望一下版针对此修订，二维码扫描应该区分是SS还是VMESS！谢谢！

**Comment by Jrohy** [comment]
确实存在这问题，会尽快修复,  谢谢反馈

**Comment by Jrohy** [comment]
https://github.com/Jrohy/v2rayN/releases/tag/2.1.2
新版修复了
