### ISSUE TITLE
改名叫v2rayN plus好了

### ISSUE THREAD

**Issue by gggccc44** [Jrohy/v2rayN#8]
不然和原版不好區分，標注基於v2rayN好了，原版還有測速功能，雖然不完美，好像沒移植過來

**Comment by Jrohy** [comment]
原版很多代码没提交的，所以也移植不了。也想提PR, 无奈太多冲突，改动比较多😂

**Comment by Justsoos** [comment]
是啊，排序什么的，都没有。原版作者貌似也不是很想开发更多功能了。这样用就行了

**Comment by jasonliul** [comment]
v2rayJ 如何?

**Comment by konbar** [comment]
希望增加重复服务器判断，今天核对了一下，发现相同服务器和相同IP好多个，那些服务器只是被一些人分享出去改成了自己的别名而已，换汤不换药啊，希望增加判断后就不会出现重复的服务器了

**Comment by Jrohy** [comment]
项目本身可能不会一直维护了，促进原版都实现了我想要的功能，就没必要两个客户端给用户选择了。目前还有类似ssr订阅更新功能没实现，多台电脑的v2rayN怎么保持一样的节点信息功能呢，感觉这个挺实用的

**Comment by Justsoos** [comment]
v2ray ssr 批量去重python脚本。 @konbar https://github.com/Justsoos/ss-ssr-v2ray-gadget#check_v2raypy-%E5%B7%A5%E5%85%B7
